from typing import Any


def make_remote_book(
    *,
    book_id: str,
    shelf: str,
    title: str,
    author: str,
    summary: str,
    cover_style: str,
    text_url: str,
    source_url: str,
    html_url: str | None = None,
) -> dict[str, Any]:
    return {
        "id": book_id,
        "shelf": shelf,
        "title": title,
        "author": author,
        "summary": summary,
        "cover_style": cover_style,
        "content_mode": "remote_book",
        "text_url": text_url,
        "html_url": html_url,
        "source_url": source_url,
    }


BOOKS: list[dict[str, Any]] = [
    make_remote_book(
        book_id="alice-gutenberg",
        shelf="Recommended",
        title="Alice's Adventures in Wonderland",
        author="Lewis Carroll",
        summary="A real public-domain illustrated book with a full reading view and source link.",
        cover_style="linear-gradient(135deg, #ff7b54 0%, #7c4dff 100%)",
        text_url="https://www.gutenberg.org/ebooks/19033.txt.utf-8",
        html_url="https://www.gutenberg.org/cache/epub/19033/pg19033-images.html",
        source_url="https://www.gutenberg.org/ebooks/19033",
    ),
    make_remote_book(
        book_id="sherlock-gutenberg",
        shelf="Recommended",
        title="The Adventures of Sherlock Holmes",
        author="Arthur Conan Doyle",
        summary="A real public-domain short story collection with a more mature mystery tone.",
        cover_style="linear-gradient(135deg, #35c9ff 0%, #0f766e 100%)",
        text_url="https://www.gutenberg.org/ebooks/1661.txt.utf-8",
        html_url="https://www.gutenberg.org/files/1661/1661-h/1661-h.htm",
        source_url="https://www.gutenberg.org/ebooks/1661",
    ),
    make_remote_book(
        book_id="secret-garden-gutenberg",
        shelf="Recommended",
        title="The Secret Garden",
        author="Frances Hodgson Burnett",
        summary="A public-domain book with a softer pace and stronger atmosphere.",
        cover_style="linear-gradient(135deg, #22c55e 0%, #14b8a6 100%)",
        text_url="https://www.gutenberg.org/ebooks/17396.txt.utf-8",
        html_url="https://www.gutenberg.org/files/17396/17396-h/17396-h.htm",
        source_url="https://www.gutenberg.org/ebooks/17396",
    ),
    make_remote_book(
        book_id="jungle-book-gutenberg",
        shelf="Recommended",
        title="The Jungle Book",
        author="Rudyard Kipling",
        summary="A public-domain collection with strong story movement and imagery.",
        cover_style="linear-gradient(135deg, #fb7185 0%, #f59e0b 100%)",
        text_url="https://www.gutenberg.org/ebooks/236.txt.utf-8",
        html_url="https://www.gutenberg.org/files/236/236-h/236-h.htm",
        source_url="https://www.gutenberg.org/ebooks/236",
    ),
    make_remote_book(
        book_id="treasure-island-gutenberg",
        shelf="Adventure Shelf",
        title="Treasure Island",
        author="Robert Louis Stevenson",
        summary="A public-domain adventure classic with a strong plot-driven feel.",
        cover_style="linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)",
        text_url="https://www.gutenberg.org/ebooks/120.txt.utf-8",
        html_url="https://www.gutenberg.org/files/120/120-h/120-h.htm",
        source_url="https://www.gutenberg.org/ebooks/120",
    ),
    make_remote_book(
        book_id="around-world-gutenberg",
        shelf="Adventure Shelf",
        title="Around the World in Eighty Days",
        author="Jules Verne",
        summary="A public-domain adventure novel with steady plot progress.",
        cover_style="linear-gradient(135deg, #34d399 0%, #10b981 100%)",
        text_url="https://www.gutenberg.org/ebooks/103.txt.utf-8",
        html_url="https://www.gutenberg.org/files/103/103-h/103-h.htm",
        source_url="https://www.gutenberg.org/ebooks/103",
    ),
    make_remote_book(
        book_id="wizard-oz-gutenberg",
        shelf="Adventure Shelf",
        title="The Wonderful Wizard of Oz",
        author="L. Frank Baum",
        summary="A public-domain illustrated classic with very recognisable imagery.",
        cover_style="linear-gradient(135deg, #f97316 0%, #ef4444 100%)",
        text_url="https://www.gutenberg.org/ebooks/55.txt.utf-8",
        html_url="https://www.gutenberg.org/files/55/55-h/55-h.htm",
        source_url="https://www.gutenberg.org/ebooks/55",
    ),
    make_remote_book(
        book_id="kidnapped-gutenberg",
        shelf="Adventure Shelf",
        title="Kidnapped",
        author="Robert Louis Stevenson",
        summary="A public-domain adventure novel with a slightly stronger challenge level.",
        cover_style="linear-gradient(135deg, #06b6d4 0%, #8b5cf6 100%)",
        text_url="https://www.gutenberg.org/ebooks/421.txt.utf-8",
        html_url="https://www.gutenberg.org/files/421/421-h/421-h.htm",
        source_url="https://www.gutenberg.org/ebooks/421",
    ),
    make_remote_book(
        book_id="anne-gutenberg",
        shelf="Calm Reads",
        title="Anne of Green Gables",
        author="L. M. Montgomery",
        summary="A public-domain book with a calmer pace that still feels mature enough.",
        cover_style="linear-gradient(135deg, #f9a8d4 0%, #c084fc 100%)",
        text_url="https://www.gutenberg.org/ebooks/45.txt.utf-8",
        html_url="https://www.gutenberg.org/files/45/45-h/45-h.htm",
        source_url="https://www.gutenberg.org/ebooks/45",
    ),
    make_remote_book(
        book_id="wind-willows-gutenberg",
        shelf="Calm Reads",
        title="The Wind in the Willows",
        author="Kenneth Grahame",
        summary="A public-domain calm read with descriptive writing and a gentler rhythm.",
        cover_style="linear-gradient(135deg, #a5b4fc 0%, #38bdf8 100%)",
        text_url="https://www.gutenberg.org/ebooks/289.txt.utf-8",
        source_url="https://www.gutenberg.org/ebooks/289",
    ),
    make_remote_book(
        book_id="little-women-gutenberg",
        shelf="Calm Reads",
        title="Little Women",
        author="Louisa May Alcott",
        summary="A public-domain classic with a more mature tone that still fits your calm shelf.",
        cover_style="linear-gradient(135deg, #fcd34d 0%, #fb7185 100%)",
        text_url="https://www.gutenberg.org/ebooks/514.txt.utf-8",
        source_url="https://www.gutenberg.org/ebooks/514",
    ),
    make_remote_book(
        book_id="christmas-carol-gutenberg",
        shelf="Calm Reads",
        title="A Christmas Carol",
        author="Charles Dickens",
        summary="A public-domain shorter classic that works well as a contained full story.",
        cover_style="linear-gradient(135deg, #4ade80 0%, #0ea5e9 100%)",
        text_url="https://www.gutenberg.org/ebooks/46.txt.utf-8",
        html_url="https://www.gutenberg.org/files/46/46-h/46-h.htm",
        source_url="https://www.gutenberg.org/ebooks/46",
    ),
]